title:              r/IBO/ Newspaper
email:              IBONP@gmail.com
description:        
author:             r/IBO/ NP Team
baseurl:            /
url:                "https://IBONP.github.io"

# Social Profiles
twitter_username:   TBD
github_username:    TBD
facebook_username:  TBD
instagram_username:  TBD
linkedin_username: TBD

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
