
name: Django test

on:
  push:
  pull_request:

jobs:
  check-types:
    name: Lint and Fix
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: set python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install deps
        run: pip install -r backend/requirements.txt

      - name: run test
        run: python ./backend/manage.py test
